"""
Generate an LLFEM-branded simulation report from Nastran F06 output.

LLFEM = LLM-generated FEM report. All AI-generated content is clearly marked
with LLFEM branding so readers know the report was written by AI.

Reads F06 files, calls Anthropic API with grounded system prompt (no outside
knowledge), embeds FEM screenshots, and outputs DOCX + PDF.

Usage:
    python pipeline/generate_simulation_report.py --run-folder <path>
    python pipeline/generate_simulation_report.py --run-folder <path> --skip-llm
    python pipeline/generate_simulation_report.py --f06 <path> --output <path>

Requires:
    ANTHROPIC_API_KEY environment variable (unless --skip-llm)
    pip install anthropic python-docx docx2pdf Pillow
"""

import sys
import os
import argparse
import glob as globmod
import re
import datetime


# ---------------------------------------------------------------------------
# LLFEM Branding Constants
# ---------------------------------------------------------------------------
LLFEM_TAG = "LLFEM"
LLFEM_FULL = "LLFEM — LLM-Generated FEM Analysis Report"
LLFEM_DISCLAIMER = (
    "This report was generated by an AI model (Claude, Anthropic) analyzing "
    "only the provided Nastran F06 output data. The AI was instructed to use "
    "no outside knowledge. All conclusions are derived solely from the data "
    "provided. Human review is recommended before making engineering decisions."
)


# ---------------------------------------------------------------------------
# F06 Parsing
# ---------------------------------------------------------------------------
def find_f06_files(run_folder):
    """Find all F06 files in the run folder."""
    matches = globmod.glob(os.path.join(run_folder, '*.f06')) + \
              globmod.glob(os.path.join(run_folder, '*.F06'))
    seen = set()
    unique = []
    for path in sorted(matches):
        norm = os.path.normcase(os.path.normpath(path))
        if norm not in seen:
            seen.add(norm)
            unique.append(path)
    return unique


def extract_f06_summary(f06_path, max_chars=80000):
    """Read F06 and extract key sections within token limits."""
    with open(f06_path, 'r', errors='ignore') as f:
        content = f.read()

    if len(content) <= max_chars:
        return content

    sections = []
    lines = content.split('\n')

    # Header
    sections.append('\n'.join(lines[:200]))

    # Eigenvalue tables
    for pattern in [r'R E A L   E I G E N V A L U E S.*?(?=\n\s*\n|\x0c)',
                    r'EIGENVALUE.*?(?=\n\s*\n|\x0c)']:
        matches = re.findall(pattern, content, re.DOTALL | re.IGNORECASE)
        for m in matches[:3]:
            sections.append(m[:5000])

    # FATAL and WARNING messages
    for line_num, line in enumerate(lines):
        if re.search(r'(FATAL|WARNING|USER INFORMATION)', line, re.IGNORECASE):
            start = max(0, line_num - 2)
            end = min(len(lines), line_num + 5)
            sections.append('\n'.join(lines[start:end]))

    # Tail
    sections.append('\n'.join(lines[-100:]))

    combined = '\n\n--- [section break] ---\n\n'.join(sections)
    return combined[:max_chars]


# ---------------------------------------------------------------------------
# LLM Report Generation
# ---------------------------------------------------------------------------
def generate_report(f06_content, f06_filename):
    """Call Anthropic API to generate simulation report."""
    try:
        import anthropic
    except ImportError:
        print("ERROR: anthropic package not installed. Run: pip install anthropic")
        sys.exit(1)

    api_key = os.environ.get('ANTHROPIC_API_KEY')
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY environment variable not set")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    system_prompt = (
        "You are a Nastran simulation analyst generating an LLFEM report. "
        "Analyze ONLY the F06 content provided to you in this message. "
        "Do not use any outside knowledge about Nastran, spacecraft, or structural "
        "analysis. If the data does not support a conclusion, say so explicitly. "
        "Never invent frequencies, results, or conclusions not present in the "
        "provided data. Flag any FATAL errors, list natural frequencies, summarize "
        "random response results, and state whether the model is healthy and "
        "DBALL-ready. Use clear section headers with ## markdown syntax."
    )

    user_prompt = (
        f"Analyze this Nastran F06 output file ({f06_filename}) and produce a "
        "simulation report with these sections:\n\n"
        "1. **Model Summary** — nodes, elements, CBUSH count, boundary conditions\n"
        "2. **Natural Frequencies** — first 10 modes with frequencies in Hz\n"
        "3. **Warnings and Fatals** — any FATAL or WARNING messages\n"
        "4. **DBALL Chain Status** — did SOL 103 and/or SOL 111 complete cleanly\n"
        "5. **Random Response Summary** — peak PSD values, dominant frequencies (if present)\n"
        "6. **Health Assessment** — is this FEM ready for the super workflow?\n\n"
        "--- BEGIN F06 CONTENT ---\n"
        f"{f06_content}\n"
        "--- END F06 CONTENT ---"
    )

    print("Calling Anthropic API (model: claude-sonnet-4-20250514)...")
    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        temperature=0,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}]
    )

    return message.content[0].text


# ---------------------------------------------------------------------------
# Image Discovery
# ---------------------------------------------------------------------------
def find_captured_images(run_folder):
    """Find captured FEM screenshot PNGs."""
    manifest = os.path.join(run_folder, "captured_images.txt")
    if os.path.isfile(manifest):
        with open(manifest, 'r') as f:
            paths = [line.strip() for line in f if line.strip()]
        return [p for p in paths if os.path.isfile(p)]

    known_images = [
        "mesh_overview.png", "boundary_conditions.png",
        "mode_shape_01.png", "mode_shape_02.png", "mode_shape_03.png",
        "cbush_locations.png", "frequency_bar_chart.png", "psd_response.png",
    ]
    found = []
    for name in known_images:
        path = os.path.join(run_folder, name)
        if os.path.isfile(path):
            found.append(path)
    return found


# Image-to-section mapping
IMAGE_SECTION_MAP = {
    "mesh_overview.png":        "Model Summary",
    "cbush_locations.png":      "Model Summary",
    "boundary_conditions.png":  "Natural Frequencies",
    "mode_shape_01.png":        "Natural Frequencies",
    "mode_shape_02.png":        "Natural Frequencies",
    "mode_shape_03.png":        "Natural Frequencies",
    "frequency_bar_chart.png":  "Natural Frequencies",
    "psd_response.png":         "Random Response",
}

IMAGE_CAPTIONS = {
    "mesh_overview.png":        "Figure: FEM Mesh Overview — 2D elevation with element coloring",
    "cbush_locations.png":      "Figure: CBUSH bolt spring locations with ground connection",
    "boundary_conditions.png":  "Figure: SPC boundary conditions (fixed base)",
    "mode_shape_01.png":        "Figure: Mode 1 — deformed shape with displacement colormap",
    "mode_shape_02.png":        "Figure: Mode 2 — deformed shape with displacement colormap",
    "mode_shape_03.png":        "Figure: Mode 3 — deformed shape with displacement colormap",
    "frequency_bar_chart.png":  "Figure: Natural frequencies (all modes) — SOL 103",
    "psd_response.png":         "Figure: PSD displacement response — SOL 111 random analysis",
}

# Order for images in appendix / within sections
IMAGE_ORDER = [
    "mesh_overview.png", "cbush_locations.png", "boundary_conditions.png",
    "mode_shape_01.png", "mode_shape_02.png", "mode_shape_03.png",
    "frequency_bar_chart.png", "psd_response.png",
]


# ---------------------------------------------------------------------------
# DOCX Report Writer
# ---------------------------------------------------------------------------
def write_docx_report(output_path, report_text, f06_filename, images, run_folder):
    """Write LLFEM-branded simulation report as DOCX with inline images."""
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor, Cm, Emu
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.section import WD_ORIENT
    except ImportError:
        print("WARNING: python-docx not installed, falling back to .md")
        return False

    doc = Document()

    # ── Style setup ──
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # ── Cover Page ──
    # LLFEM badge
    llfem_para = doc.add_paragraph()
    llfem_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    llfem_run = llfem_para.add_run(f"[ {LLFEM_TAG} ]")
    llfem_run.bold = True
    llfem_run.font.size = Pt(28)
    llfem_run.font.color.rgb = RGBColor(0x25, 0x63, 0xEB)

    # Spacer
    doc.add_paragraph()

    # Title
    title = doc.add_heading("Nastran Simulation Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub.add_run("AI-Generated Structural Analysis Report")
    sub_run.font.size = Pt(14)
    sub_run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()

    # Metadata table
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    meta_items = [
        ("Generated", now),
        ("F06 Files", f06_filename),
        ("Generator", "Claude (Anthropic API, temperature=0)"),
        ("Report Type", LLFEM_FULL),
        ("FEM Images", f"{len(images)} screenshots embedded" if images else "None"),
    ]
    table = doc.add_table(rows=len(meta_items), cols=2)
    table.style = 'Light Grid Accent 1'
    for i, (key, val) in enumerate(meta_items):
        row = table.rows[i]
        row.cells[0].text = key
        row.cells[1].text = val
        # Bold keys
        for paragraph in row.cells[0].paragraphs:
            for run in paragraph.runs:
                run.bold = True

    doc.add_paragraph()

    # LLFEM Disclaimer box
    disclaimer = doc.add_paragraph()
    disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    d_run = disclaimer.add_run(f"⚠ {LLFEM_TAG} DISCLAIMER\n")
    d_run.bold = True
    d_run.font.size = Pt(10)
    d_run.font.color.rgb = RGBColor(0xDC, 0x26, 0x26)
    d_run2 = disclaimer.add_run(LLFEM_DISCLAIMER)
    d_run2.font.size = Pt(9)
    d_run2.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
    d_run2.italic = True

    doc.add_page_break()

    # ── FEM Visualization Gallery (before LLM analysis) ──
    if images:
        doc.add_heading("FEM Visualizations", level=1)
        gallery_note = doc.add_paragraph()
        gn_run = gallery_note.add_run(
            "The following figures were generated automatically from the Nastran "
            "model (DAT) and results (OP2) files using pyNastran and Matplotlib. "
            "These are not AI-generated — they are direct renderings of the FEM data."
        )
        gn_run.font.size = Pt(10)
        gn_run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
        gn_run.italic = True

        doc.add_paragraph()

        # Insert images in defined order
        ordered_images = []
        for img_name in IMAGE_ORDER:
            for img_path in images:
                if os.path.basename(img_path) == img_name:
                    ordered_images.append(img_path)
                    break
        # Add any images not in the predefined order
        for img_path in images:
            if img_path not in ordered_images:
                ordered_images.append(img_path)

        for img_path in ordered_images:
            img_name = os.path.basename(img_path)
            caption = IMAGE_CAPTIONS.get(img_name, f"Figure: {img_name}")

            try:
                # Use wider width for landscape-oriented charts
                if 'bar_chart' in img_name or 'psd_response' in img_name:
                    width = Inches(6.5)
                else:
                    width = Inches(4.5)

                doc.add_picture(img_path, width=width)
                last_p = doc.paragraphs[-1]
                last_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

                cap_p = doc.add_paragraph()
                cap_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                cap_run = cap_p.add_run(caption)
                cap_run.italic = True
                cap_run.font.size = Pt(9)
                cap_run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

                doc.add_paragraph()  # spacing

            except Exception as e:
                doc.add_paragraph(f"[Image not available: {img_name} — {e}]")

        doc.add_page_break()

    # ── LLFEM Analysis Section ──
    llfem_header = doc.add_heading(f"{LLFEM_TAG} Analysis", level=1)

    # LLFEM badge before analysis
    badge = doc.add_paragraph()
    badge_run = badge.add_run(f"[ {LLFEM_TAG} — The following analysis was generated by AI ]")
    badge_run.bold = True
    badge_run.font.size = Pt(10)
    badge_run.font.color.rgb = RGBColor(0x25, 0x63, 0xEB)
    badge.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    # ── Parse LLM markdown into DOCX paragraphs ──
    lines = report_text.split('\n')
    in_list = False

    for line in lines:
        stripped = line.strip()

        if not stripped:
            if in_list:
                in_list = False
            continue

        # Section headers
        if stripped.startswith('## ') or stripped.startswith('# '):
            heading_text = stripped.lstrip('#').strip()
            level = 2 if stripped.startswith('## ') else 1
            doc.add_heading(heading_text, level=min(level + 1, 4))

        # Bold subheadings like **From fixed_base_beam.f06:**
        elif stripped.startswith('**') and stripped.endswith('**'):
            p = doc.add_paragraph()
            p.add_run(stripped.strip('*')).bold = True

        # Bold then colon: **Key:** value
        elif stripped.startswith('**') and '**' in stripped[2:]:
            p = doc.add_paragraph()
            # Split on closing **
            match = re.match(r'\*\*(.+?)\*\*(.*)$', stripped)
            if match:
                p.add_run(match.group(1)).bold = True
                rest = match.group(2).strip()
                if rest:
                    p.add_run(f" {rest}")
            else:
                p.add_run(stripped.replace('**', ''))

        # Numbered list: 1. item
        elif re.match(r'^\d+\.\s', stripped):
            text = re.sub(r'^\d+\.\s', '', stripped)
            # Handle bold within list items
            p = doc.add_paragraph(style='List Number')
            _add_formatted_runs(p, text)
            in_list = True

        # Bullet points
        elif stripped.startswith('- ') or stripped.startswith('* '):
            text = stripped[2:]
            p = doc.add_paragraph(style='List Bullet')
            _add_formatted_runs(p, text)
            in_list = True

        # Checkmark items (✅ ⚠ ❌)
        elif stripped[0] in '✅⚠❌':
            p = doc.add_paragraph()
            _add_formatted_runs(p, stripped)

        # Regular text
        else:
            p = doc.add_paragraph()
            _add_formatted_runs(p, stripped)

    # ── Footer with LLFEM stamp ──
    doc.add_paragraph()
    doc.add_paragraph()
    footer_line = doc.add_paragraph()
    footer_line.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fl_run = footer_line.add_run("— " * 20)
    fl_run.font.color.rgb = RGBColor(0xD1, 0xD5, 0xDB)

    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    f_run = footer.add_run(
        f"{LLFEM_TAG} Report  |  Generated {now}  |  "
        f"Claude (Anthropic, temperature=0)  |  "
        f"Human review recommended"
    )
    f_run.font.size = Pt(8)
    f_run.font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)
    f_run.italic = True

    doc.save(output_path)
    return True


def _add_formatted_runs(paragraph, text):
    """Parse inline markdown bold (**text**) into Word runs."""
    parts = re.split(r'(\*\*.*?\*\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            paragraph.add_run(part)


# ---------------------------------------------------------------------------
# PDF Conversion
# ---------------------------------------------------------------------------
def convert_to_pdf(docx_path):
    """Convert DOCX to PDF using docx2pdf (requires Microsoft Word)."""
    pdf_path = docx_path.replace('.docx', '.pdf')

    try:
        from docx2pdf import convert
        print(f"Converting to PDF: {os.path.basename(pdf_path)}...")
        convert(docx_path, pdf_path)
        if os.path.isfile(pdf_path) and os.path.getsize(pdf_path) > 0:
            print(f"PDF generated: {pdf_path}")
            return pdf_path
        else:
            print("WARNING: PDF conversion produced empty file")
            return None
    except ImportError:
        print("WARNING: docx2pdf not installed — skipping PDF. Run: pip install docx2pdf")
        return None
    except Exception as e:
        print(f"WARNING: PDF conversion failed: {e}")
        return None


# ---------------------------------------------------------------------------
# Markdown Fallback
# ---------------------------------------------------------------------------
def write_md_report(output_path, report_text, f06_filename):
    """Write report as Markdown (fallback)."""
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(f"# {LLFEM_TAG} — Nastran Simulation Report\n\n")
        f.write(f"**Generated:** {now}  \n")
        f.write(f"**F06 Files:** {f06_filename}  \n")
        f.write(f"**Generator:** Claude (Anthropic API, temperature=0)  \n")
        f.write(f"**Report Type:** {LLFEM_FULL}  \n\n")
        f.write(f"> ⚠ **{LLFEM_TAG} DISCLAIMER:** {LLFEM_DISCLAIMER}\n\n")
        f.write("---\n\n")
        f.write(report_text)
        f.write("\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Generate LLFEM simulation report")
    parser.add_argument('--run-folder', help='Path to timestamped run folder')
    parser.add_argument('--f06', help='Path to specific F06 file')
    parser.add_argument('--output', help='Output path for report')
    parser.add_argument('--skip-llm', action='store_true', default=False,
                        help='Skip LLM call — generate report with images only (no AI analysis)')
    parser.add_argument('--docx', action='store_true', default=False,
                        help='Force DOCX output')
    parser.add_argument('--pdf', action='store_true', default=True,
                        help='Also generate PDF from DOCX (default: True)')
    parser.add_argument('--no-pdf', action='store_true', default=False,
                        help='Disable PDF generation')
    args = parser.parse_args()

    run_folder = args.run_folder or (os.path.dirname(args.f06) if args.f06 else None)
    if not run_folder:
        print("ERROR: Specify --run-folder or --f06")
        sys.exit(1)

    # Find F06 files
    if args.run_folder:
        f06_files = find_f06_files(args.run_folder)
    elif args.f06:
        f06_files = [args.f06]
    else:
        f06_files = []

    if not f06_files and not args.skip_llm:
        print("ERROR: No F06 files found (use --skip-llm for image-only report)")
        sys.exit(1)

    if f06_files:
        print(f"Found {len(f06_files)} F06 file(s)")

    # Check for captured images
    images = find_captured_images(run_folder)
    if images:
        print(f"Found {len(images)} captured FEM image(s)")

    # Auto-enable DOCX if images available
    use_docx = args.docx or len(images) > 0

    # Generate LLM report text
    if args.skip_llm:
        report_text = (
            "## LLFEM Analysis\n\n"
            "LLM analysis was skipped for this report. "
            "See FEM visualizations above for model overview.\n"
        )
        combined_filename = "N/A (--skip-llm)"
    else:
        all_content = []
        for f06_path in f06_files:
            fname = os.path.basename(f06_path)
            print(f"  Reading: {fname}")
            content = extract_f06_summary(f06_path)
            all_content.append(f"=== {fname} ===\n{content}")

        combined_content = '\n\n'.join(all_content)
        combined_filename = ', '.join(os.path.basename(f) for f in f06_files)
        report_text = generate_report(combined_content, combined_filename)

    # Write DOCX report
    if use_docx:
        output_path = args.output or os.path.join(run_folder, 'simulation_report.docx')
        success = write_docx_report(output_path, report_text, combined_filename,
                                     images, run_folder)
        if not success:
            output_path = os.path.join(run_folder, 'simulation_report.md')
            write_md_report(output_path, report_text, combined_filename)
        elif not args.no_pdf:
            convert_to_pdf(output_path)
    else:
        output_path = args.output or os.path.join(run_folder, 'simulation_report.md')
        write_md_report(output_path, report_text, combined_filename)

    # Always write .md backup
    md_path = os.path.join(run_folder, 'simulation_report.md')
    if output_path != md_path:
        write_md_report(md_path, report_text, combined_filename)
        print(f"Markdown backup: {md_path}")

    print(f"\nReport written to: {output_path}")

    # GITHUB_OUTPUT
    github_output = os.environ.get('GITHUB_OUTPUT')
    if github_output:
        with open(github_output, 'a') as f:
            f.write(f"REPORT_PATH={output_path}\n")
            f.write(f"REPORT_FORMAT={'docx' if use_docx else 'md'}\n")


if __name__ == '__main__':
    main()
